# Site settings
title:          "Smart's Home"
description:    "База знаний по домашней автоматизации"
baseurl:        "/"
url:            "https://smartshome.github.io"

# Build settings
markdown:       kramdown

theme: jekyll-theme-slate
