# Site settings
title:          "Smart Home"
description:    "Smart Home"
baseurl:        "/"
url:            "https://smartshome.github.io"

# Build settings
markdown:       kramdown

theme: jekyll-theme-slate